console.log('Hello I am from Playground!');
var myString;
var myNum;
var myBool;
var mystrArray;
var mynumArray;
var myboolArray;
var myAnything;
var myTuple;
var myVoid;
var myNull;
var myUndefined;
myString = "I am from variable";
myNum = 22;
myBool = true;
mystrArray = ["I", "AM", "STRING", "ARRAY"];
mynumArray = [1, 2, 3, 4, 5];
myboolArray = [true, false, true];
myAnything = true;
myTuple = ["Hello", 1, true];
myVoid = undefined;
myNull = null;
myUndefined = undefined;
console.log(myNum);
console.log(myString);
console.log(mystrArray);
console.log(mynumArray);
console.log(myboolArray);
console.log(myAnything);
console.log(myTuple);
console.log(myVoid);
console.log(myNull);
console.log(myUndefined);
